name: PGDM Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install -r requirements.txt

      - run: python reminder/main.py
        env:
          OUTLOOK_EMAIL: ${{ secrets.OUTLOOK_EMAIL }}
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
